AllCops:
  Exclude:
    - spec/dummy/**/*
    - lib/generators/**/*
    - vendor/bundle/**/*
  RunRailsCops: true

ClassLength:
  Max: 125

HandleExceptions:
  Enabled: False

LineLength:
  Max: 100

CyclomaticComplexity:
  Max: 10

DoubleNegation:
  Enabled: False

MethodLength:
  Max: 30

Documentation:
  Enabled: false

StringLiterals:
  Enabled: false

