sudo: false
language: ruby
rvm:
  - "2.3.4"
  - "2.4.1"
services:
  - memcached
before_script:
  - export TZ='Europe/Berlin'
script:
  - bundle exec rake
after_script:
  - CODECLIMATE_REPO_TOKEN=a0a2bb8de1052f04e02943c208909e1ee43feed7 bundle exec codeclimate-test-reporter
gemfile:
  - Gemfile
  - gemfiles/Gemfile-4.2
