sudo: false
language: ruby
rvm:
  - "2.2.2"
  - "2.3.0"
before_script:
  - export TZ='Europe/Berlin'
script:
  - bundle exec rake
after_script:
  - CODECLIMATE_REPO_TOKEN=97304c6d5e6017ffcf39bb7220a40d37062205ae6b8989a712ac0631b9122111 bundle exec codeclimate-test-reporter
gemfile:
  - Gemfile
  - gemfiles/Gemfile-4.2
