renderer:
  teaser:
    render_type: resize_crop
    format: jpeg
    x: 960
    y: 444
    hires_factor: 2
  customized:
    render_type: resize_customized
    customized_converter: customize_converter
    format: jpeg
    x: 960
    y: 444
    hires_factor: 2  
