renderer:
  teaser:
    render_type: resize_crop
    format: jpeg
    x: 960
    y: 444
    hires_factor: 2
  customized:
    render_type: render_class_name
    render_class_name: CustomizeConverter
    format: jpeg
    x: 960
    y: 444
    hires_factor: 2  
